### ISSUE TITLE
Automate docker image build and push to VPS

### ISSUE THREAD

**Issue by elgorditosalsero** [elgorditosalsero/job-offer-bot#4]
# Automate docker image build and push to VPS

### Feature type

- [x] Idea
- [ ] Problem/Issue
- [ ] Other

## Idea

I'd love to automate the creation of the image when there are new merges into `main` to not have to deploy the bot manually and restart it via docker.

## Proposal

I'm looking for help 😄 

### Alternatives

Please tell me 😄

**Comment by fedy97** [comment]
Hi @elgorditosalsero you could use this Github Action, by editing the last script if you do not want to use `docker-compose`.  You can put `secrets` to `Settings` -> `Secrets and variables` -> `Actions`

```yaml
name: Deploy Node App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: ${{ secrets.TARGET_PATH }}

      - name: Build and Run Docker Container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd {{ secrets.TARGET_PATH }}
            docker-compose up --build -d
```

**Comment by fedy97** [comment]
If you already have a `.env` file in the same directory as the `docker-compose.yaml` file, docker should automatically read it. Otherwise, you can change the command to `docker-compose --env-file /custom/path/custom.env --build up`

**Comment by elgorditosalsero** [comment]
> If you already have a `.env` file in the same directory as the `docker-compose.yaml` file, docker should automatically read it. Otherwise, you can change the command to `docker-compose --env-file /path/to/your/.env up --build -d`

Yeah, but I'm referring to the .env for the project, I'd love to avoid to write it directly on the VPS, as if I want to make some changes, I always have to login there, but I can handle them via the secrets here would be probably be better 😄 

I have to do some research about it

**Comment by fedy97** [comment]
> > If you already have a `.env` file in the same directory as the `docker-compose.yaml` file, docker should automatically read it. Otherwise, you can change the command to `docker-compose --env-file /path/to/your/.env up --build -d`
> 
> Yeah, but I'm referring to the .env for the project, I'd love to avoid to write it directly on the VPS, as if I want to make some changes, I always have to login there, but I can handle them via the secrets here would be probably be better 😄
> 
> I have to do some research about it

@elgorditosalsero a brutal way of doing that would be to edit the last action in something like this
```yaml
- name: Build and Run Docker Container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.TARGET_PATH }}
            # Export your secrets as environment variables
            export SECRET1="${{ secrets.SECRET1 }}"
            export SECRET2="${{ secrets.SECRET2 }}"
            docker-compose up --build -d
```
so that all the secrets stored in github are exported each time a new deploy is triggered. Let's see if someone else has a smarter solution
